In [1]:
import ej1
import test_ej1
import ej2
import test_ej2
import ej3
import test_ej3
import numpy as np

In [2]:
# Tridiagonal
# Caso matriz singular 3
mat_sing = np.array([[1, 2, 0], [1, 2, 0], [0, 1, 2]])
x_ini = np.array([1, 1, 1])
d = np.dot(mat_sing, x_ini)

"""
120    120
120 -> 000
012    012
"""


c = np.array([2, 0, 0])
b = np.array([1, 2, 2])
a = np.array([0, 1, 1])

test_ej3.paso_a_lista_y_ejecuto(a, b, c, d)

Error: division por cero


array([0., 0., 0.])

In [3]:
# Tridiagonal
# Caso matriz singular 4
mat_sing = np.array([[1, 2, 0], [2, 5, 1], [0, 1, 1]])

x_ini = np.array([1, 1, 1])
d = np.dot(mat_sing, x_ini)

"""
120    120    120
251 -> 011 -> 011
011    011    000
"""


c = np.array([2, 1, 0])
b = np.array([1, 5, 1])
a = np.array([0, 2, 1])

test_ej3.paso_a_lista_y_ejecuto(a, b, c, d)
# No esta pensado usar la tridiagonal con precomputo con una matriz singular

Matriz singular sin solucion unica


array([0., 0., 0.])

# Puntos de enunciado

##### 1a) "... Debe devolver una excepción si no puede encontrar la solución."

In [4]:
# EG sin pivoteo
# Caso matriz singular 1
mat_sing = np.array([[1, 2, 1], [2, 4, 2], [0, 0, 1]])
x_ini = np.array([1, 1, 1])
d = np.dot(mat_sing, x_ini)

test_ej1.paso_a_lista_y_ejecuto(mat_sing, d)

No se puede realizar la EG sin pivoteo (division por 0)


array([0., 0., 0.])

In [5]:
# EG sin pivoteo
# Caso matriz singular 2 (ultima fila 0s)
mat_sing = np.array([[1, 2, 1], [1, 3, 2], [0, 1, 1]])
x_ini = np.array([1, 1, 1])
d = np.dot(mat_sing, x_ini)

test_ej1.paso_a_lista_y_ejecuto(mat_sing, d)

El sistema no tiene solucion unica (matriz singular)


array([0., 0., 0.])

###### 1b) Encontrar un ejemplo donde el algoritmo no se puede aplicar pero si hubiese pivoteo si.

In [6]:
# EG con y sin pivoteo
# Caso matriz no singular (matriz identidad permutada)
mat_id_perm = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
x_ini = np.array([1, 2, 3])
d = np.dot(mat_id_perm, x_ini)

print("EG sin pivoteo:")
print(test_ej1.paso_a_lista_y_ejecuto(mat_id_perm, d))
print("==========")
print("EG con pivoteo: ")
print(test_ej2.paso_a_lista_y_ejecuto(mat_id_perm, d))
print("==========")
print("Solucion:")
print(x_ini)

EG sin pivoteo:
No se puede realizar la EG sin pivoteo (division por 0)
[0. 0. 0.]
EG con pivoteo: 
[1. 2. 3.]
Solucion:
[1 2 3]


##### 2) b) Encontrar un ejemplo donde el algoritmo no se puede aplicar por que el sistema no tiene soluciones o tiene infinitas.

In [7]:
# EG con pivoteo
# Caso matriz singular 1
mat_sing = np.array([[1, 2, 1], [2, 4, 2], [0, 0, 1]])
x_ini = np.array([1, 1, 1])
d = np.dot(mat_sing, x_ini)

test_ej2.paso_a_lista_y_ejecuto(mat_sing, d)

El sistema tiene infinitas soluciones


array([0., 0., 0.])

In [8]:
# EG con pivoteo
# Caso matriz singular 2 (ultima fila = 0)
# En este caso d = [4, 6, 2]

mat_sing = np.array([[1, 2, 1], [1, 3, 2], [0, 1, 1]])
x_ini = np.array([1, 1, 1])
d = np.dot(mat_sing, x_ini)

test_ej2.paso_a_lista_y_ejecuto(mat_sing, d)

El sistema tiene infinitas soluciones


array([0., 0., 0.])

In [9]:
# EG con pivoteo
# Caso matriz singular 2, pero con vec. indep. que no haya sol.
# En este caso d = [4, 6, 1]

mat_sing = np.array([[1, 2, 1], [1, 3, 2], [0, 1, 1]])
d = np.array([4, 6, 1])

test_ej2.paso_a_lista_y_ejecuto(mat_sing, d)

El sistema no tiene solucion


array([0., 0., 0.])

##### 2) d) Encontrar un ejemplo donde el algoritmo entrega un resultado aproximado por error numérico.

In [10]:
# HACER